---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: bug
assignees: kus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us locate and squash bugs!
  - type: checkboxes
    id: up-to-date
    attributes:
      label: Server is up to date
      description: You are using the latest version from this github.
      options:
        - label: My server is up-to-date and I'm using the latest version of this mod from this github.
          required: true
  - type: checkboxes
    id: instructions
    attributes:
      label: I've followed the instructions
      description: I've followed the [simple quick setup](https://github.com/kus/cs2-modded-server#about) instructions.
      options:
        - label: I've followed the instructions
          required: true
  - type: checkboxes
    id: token
    attributes:
      label: Game Server Login Token
      description: If hosting online; I've made a [Game Server Login Token](https://steamcommunity.com/dev/managegameservers) and it hasn't expired. If hosting on LAN; you do not need this.
      options:
        - label: I'm using a valid Game Server Login Token or running on LAN
          required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      multiple: true
      options:
        - Linux Ubuntu 22.04
        - Linux Ubuntu 20.04
        - Linux Ubuntu 18.04
        - Linux Ubuntu 16.04
        - Linux Debian 11
        - Linux Debian 10
        - Linux Debian 9
        - Linux RedHat 9
        - Linux RedHat 8
        - Linux RedHat 7
        - Linux Other (please specify)
        - Windows 11
        - Windows 10
        - Windows 8.1
        - Windows 8
        - Windows 7
        - Windows Server 2022
        - Windows Server 2019
        - Windows Server 2016
        - Windows Server 2012
        - Other (please specify)
    validations:
      required: true
  - type: dropdown
    id: mod
    attributes:
      label: Which mod are you playing
      multiple: true
      options:
        - No mod
        - Competitive
        - Deathmatch
        - Wingman
        - 1v1
        - Practice
        - Surf
        - Bhop
        - KZ
        - Other (please specify)
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: Are you trying to host online or on LAN?
      multiple: true
      options:
        - Online on a cloud host Google, AWS, Azure etc (please specify host)
        - Online on a game hosting network (please specify host)
        - Online off a machine on my local network
        - Online off my machine
        - LAN off a machine on my local network
        - LAN off my machine
    validations:
      required: true
  - type: input
    id: meta-version
    attributes:
      label: Metamod:Source Version
      description: Output of `meta version` from console.
    validations:
      required: true
  - type: input
    id: meta-list
    attributes:
      label: Metamod:Source Plugins loaded
      description: Output of `meta list` from console.
    validations:
      required: true
  - type: input
    id: css-version
    attributes:
      label: CounterStrikeSharp Version
      description: Output of `css` from console.
    validations:
      required: true
  - type: input
    id: css-list
    attributes:
      label: CounterStrikeSharp Plugins loaded
      description: Output of `css_plugins list` from console.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: What is the bug
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: console
    attributes:
      label: Game console output
      description: Please copy and paste any the relevant output from the game console (~) when you join the server as a player.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Server log output
      description: Please copy and paste any the relevant output from the server logs.
      render: shell
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. Using Windows/Linux; Load the server
        2. Join the server as player
        3. Open admin menu and change mod to ...
        4. See error
