---
name: Feature Request
description: Suggest a feature
title: "[Feature]: "
labels: feature
assignees: kus
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: info
    attributes:
      label: Information
      description: A clear description of what the feature is and any ideas on how to achieve this.
    validations:
      required: true
